In [274]:
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

# from torcheval.metrics.functional import binary_accuracy


In [275]:
# import data.tsv file and create a dataframe

df = pd.read_csv('data.tsv', sep='\t')

# open file data_info.txt and read the first line

sequence_length = None
with open('data_info.txt', 'r') as f:
    line = f.readline()
    split_line_on_collen = line.split(':')
    sequence_length = int(split_line_on_collen[1])
    


train_df = df.sample(frac=0.8, random_state=0)
test_df = df.drop(train_df.index)


# drop the collumn Y from the dataframe

train_x = train_df.drop(['Y'], axis=1).iloc[1:]
train_y = train_df['Y'].iloc[1:]

# make the tran_x data rows have the same length as the sequence_length by padding with [0,0,0] for each collumn

# train_x = train_x.reindex(range(sequence_length), fill_value=[0,0,0])

test_x = test_df.drop(['Y'], axis=1)


test_y = test_df['Y']



In [276]:
def convert_rows_to_nupy_array(df):
    numpy_array = []
    for index, row in df.iterrows():
        row_array = []
        for col in row.iteritems():
            col_float = []
            for item in col[1].split(','):
                col_float.append(float(item.replace('[', '').replace(']', '')))
            row_array.append(col_float)
        numpy_array.append(row_array)
    return np.array(numpy_array)

train_x_numpy = convert_rows_to_nupy_array(train_x)
test_x_numpy = convert_rows_to_nupy_array(test_x)

print(train_x_numpy.shape)
print(test_x_numpy[1][5])
            

(2057, 749, 3)
[ 0.51171875 -0.10406494 -0.10406494]


##### Remove Padding from numpy

In [277]:
train_y_no_pad = train_y
test_y_no_pad = test_y

# remove the numpy array where you hava a [0,0,0] array

test_np_array = np.array([[1,2,1], [0,0,0], [1,2,1]])

# remove the [0,0,0] array from the numpy array test_np_array

test_np_array = test_np_array[test_np_array[:,0] != 0]



train_x_numpy_no_pad = []
# row_index = 0
for row in range(len(train_x_numpy)):
    temp = train_x_numpy[row][train_x_numpy[row][:,0] != 0]
    temp_list = []
    for col in temp:
        item_list = []
        for item in col:
            item_list.append(item)
        temp_list.append(item_list)
    train_x_numpy_no_pad.append(temp_list)
train_x_numpy_no_pad = np.array(train_x_numpy_no_pad)
print(train_x_numpy_no_pad.shape)


(2057,)


/tmp/ipykernel_13502/3299080516.py:25: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  train_x_numpy_no_pad = np.array(train_x_numpy_no_pad)


## Train

In [278]:
# Dummy Classifer

from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score

dummy_clf = DummyClassifier(strategy="most_frequent")
print(train_x_numpy.shape, train_y.shape)
dummy_clf.fit(train_x_numpy, train_y)
y_pred = dummy_clf.predict(test_x_numpy)
print(accuracy_score(test_y, y_pred))

(2057, 749, 3) (2057,)
0.7704280155642024


In [279]:

class MyDataset(torch.utils.data.Dataset):
    def __init__(self, input,target, seq_len):
        self.input = input
        self.target = target
        self.seq_len = seq_len
    def __getitem__(self, item):
        # print("input item", self.input[item])
        return self.input[item], self.target.iloc[item]

        # return input[item:item+self.seq_len], input[item+self.seq_len]
    def __len__(self):
        return  self.input.shape[0]

# test_input = np.arange(1,8).reshape(-1,1)
# input = torch.tensor(test_input, dtype=torch.float)

# dataset = MyDataset(input, 3)

# dl = torch.utils.data.DataLoader(dataset, batch_size=1)
# for inp, label in dl:
#     print("inp shape",inp.shape)
#     print("inp",inp.numpy())


device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")


input_size = 3
num_classes = 1
hidden_size = 64
num_layers = 2
learning_rate = 0.005

class SitUpDetector(nn.Module):
    def __init__(self,input_size, num_classes, hidden_size, num_layers,drop_prob=0.5):
        super(SitUpDetector, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers,dropout=drop_prob, batch_first=True)
        self.dropout = nn.Dropout(drop_prob)
        self.fc = nn.Linear(hidden_size, num_classes)
        self.sigmoid = nn.Sigmoid()


    def forward(self, x, hidden):
        batch_size = x.size(0)
        out, _ = self.lstm(x, hidden)
        out = out.contiguous().view(-1, self.hidden_size)
        out = self.dropout(out)
        out = self.fc(out)
        out = self.sigmoid(out)

        out = out.view(batch_size, -1)
        out = out[:, -1]
        return out,hidden

    def init_hidden(self, batch_size):
        weight = next(self.parameters()).data
        hidden = (weight.new(self.num_layers, batch_size, self.hidden_size).zero_().float().to(device),
                      weight.new(self.num_layers, batch_size, self.hidden_size).zero_().float().to(device)) 
        return hidden
    


model = SitUpDetector(input_size, num_classes, hidden_size, num_layers).to(device)
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
# reduce size of train_x_numpy_no_pad to 1000
# train_x_numpy = train_x_numpy[:50]
# train_y = train_y[:50]

# test_x_numpy = test_x_numpy[:50]
# test_y = test_y[:50]


# print how many 1 and 0 in the train_y
print(train_y.value_counts())

batch_size = 1

myDataset = MyDataset(train_x_numpy,train_y, sequence_length)
train_loader = torch.utils.data.DataLoader(dataset=myDataset, batch_size=batch_size)

losses = []
loss = None
num_epochs = 2
clip = 5
valid_loss_min = np.Inf
total_steps = len(train_loader)

model.train()
for epoch in range(num_epochs):
    h = model.init_hidden(batch_size)
    for i, (features, target) in enumerate(train_loader):


        h = tuple([e.data for e in h])

        # convert Double tensor to Float tensor
        # features = features.float()

        features, target = features.to(device), target.to(device)
        model.zero_grad()
        outputs, h = model(features.float(), h)
        loss = criterion(outputs, target.float())
        losses.append(loss)
        nn.utils.clip_grad_norm_(model.parameters(), clip)
        loss.backward()

        optimizer.step()
        if (i+1) % 50 == 0:
            val_h = model.init_hidden(batch_size)
            val_losses = []
            model.eval()
            for inp, lab in train_loader:
                val_h = tuple([each.data for each in val_h])
                inp, lab = inp.to(device), lab.to(device)
                out, val_h = model(inp.float(), val_h)
                val_loss = criterion(out, lab.float())
                val_losses.append(val_loss.item())
                
            model.train()
            print("Epoch: {}/{}...".format(epoch+1, num_epochs),
                  "Step: {}...".format(i),
                  "Loss: {:.6f}...".format(loss.item()),
                  "Val Loss: {:.6f}".format(np.mean(val_losses)))
            if np.mean(val_losses) <= valid_loss_min:
                torch.save(model.state_dict(), './state_dict.pt')
                print('Validation loss decreased ({:.6f} --> {:.6f}).  Saving model ...'.format(valid_loss_min,np.mean(val_losses)))
                valid_loss_min = np.mean(val_losses)

# graph the losses 

# get the lenght of the losses array

# create an array of the same length as the losses array with index values

y = np.array(losses)
print("y shpae")
print(y)

x = np.arange(0,num_epochs)
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.plot()
plt.show()






# Confusion Matrix
# from sklearn.metrics import confusion_matrix
# import seaborn as sns
# import matplotlib.pyplot as plt

# cm = confusion_matrix(test_y, all_predictions)
# print(cm)
# sns.heatmap(cm, annot=True, fmt="d")

torch.save(model.state_dict(), 'sit_up_detector.pth')






0    1513
1     544
Name: Y, dtype: int64
Epoch: 50/2... Step: 49... Loss: 0.100714... Val Loss: 0.702114
Validation loss decreased (inf --> 0.702114).  Saving model ...
Epoch: 100/2... Step: 99... Loss: 2.846028... Val Loss: 0.792848
Epoch: 150/2... Step: 149... Loss: 1.358052... Val Loss: 0.578241
Validation loss decreased (0.702114 --> 0.578241).  Saving model ...
Epoch: 200/2... Step: 199... Loss: 1.310449... Val Loss: 0.580937
Epoch: 250/2... Step: 249... Loss: 0.182626... Val Loss: 0.577685
Validation loss decreased (0.578241 --> 0.577685).  Saving model ...
Epoch: 300/2... Step: 299... Loss: 0.141326... Val Loss: 0.668930
Epoch: 350/2... Step: 349... Loss: 0.203027... Val Loss: 0.578805
Epoch: 400/2... Step: 399... Loss: 0.370640... Val Loss: 0.581418


In [ ]:
# Check accuracy
test_dataset = MyDataset(train_x_numpy,train_y, sequence_length)
test_dataloader = torch.utils.data.DataLoader(dataset=test_dataset, batch_size=1)
n_correct = 0
n_samples = 0
model.eval()

all_predictions = []


test_losses = []
num_correct = 0
h = model.init_hidden(batch_size)


model.eval()
for inputs, label in test_dataloader:
    h = tuple([each.data for each in h])
    inputs, label = inputs.to(device), label.to(device)
    output, h = model(inputs.float(), h)
    test_loss = criterion(output, label.float())
    test_losses.append(test_loss.item())
    pred = torch.round(output.squeeze())  # Rounds the output to 0/1
    correct_tensor = pred.eq(label.float().view_as(pred))
    correct = np.squeeze(correct_tensor.cpu().numpy())
    num_correct += np.sum(correct)

print("Test loss: {:.3f}".format(np.mean(test_losses)))
test_acc = num_correct/len(test_dataloader.dataset)
print("Test accuracy: {:.3f}%".format(test_acc*100))

test y 0      1
3      1
7      1
21     1
24     1
25     1
26     1
63     1
67     1
84     1
86     1
91     1
93     1
94     1
99     1
100    1
112    1
126    1
130    1
136    1
146    1
151    1
153    1
160    1
163    1
164    1
166    1
168    1
174    1
176    1
180    1
197    1
199    1
201    1
207    1
209    1
216    1
221    1
237    1
246    1
256    1
257    1
273    1
274    1
275    1
277    1
280    1
281    1
282    1
291    1
Name: Y, dtype: int64
label
tensor([0])
labels
tensor([0])
label
tensor([0])
labels
tensor([0])
label
tensor([1])
labels
tensor([1])
label
tensor([0])
labels
tensor([0])
label
tensor([1])
labels
tensor([1])
label
tensor([0])
labels
tensor([0])
label
tensor([0])
labels
tensor([0])
label
tensor([1])
labels
tensor([1])
label
tensor([0])
labels
tensor([0])
label
tensor([0])
labels
tensor([0])
label
tensor([0])
labels
tensor([0])
label
tensor([0])
labels
tensor([0])
label
tensor([0])
labels
tensor([0])
label
tensor([0])
labels
tensor([0])
lab

# Train with no Padding

In [ ]:
class MyDatasetVariableSequenceLength(torch.utils.data.Dataset):
    def __init__(self, input,target, seq_len):
        self.input = input
        self.target = target
        self.seq_len = seq_len
    def __getitem__(self, item):
        # print("input item", self.input[item])
        return self.input[item], self.target.iloc[item]

        # return input[item:item+self.seq_len], input[item+self.seq_len]
    def __len__(self):
        return self.input.shape[0]

In [ ]:
#  create pytorch lstm variable recurrent classifier

input_size = 3
num_classes = 1
hidden_size = 256
num_layers = 2
learning_rate = 0.001


class SitUpDetectorVariableSequenceLength(nn.Module):
    def __init__(self,input_size, num_classes, hidden_size, num_layers):
        super(SitUpDetectorVariableSequenceLength, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True, bidirectional=True)
        self.fc = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        outputs = []
        
        # x = torch.squeeze(x) # remove the batch dimension maybe sometime allow for batch size > 1
        
        for xx in x:
            s, n = xx.shape
            print(xx.shape)
            out, _ = self.lstm(xx)
            out = out.view(s, -1)
            outputs.append(out)

        outputs = torch.stack(outputs)

        out = self.fc(outputs)
        return out

# train SitUpDetectorVariableInput
model = SitUpDetectorVariableSequenceLength(input_size, num_classes, hidden_size, num_layers).to(device)
criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

myDatasetVariableSequenceLengthDataset = MyDatasetVariableSequenceLength(train_x_numpy,train_y, sequence_length)
train_loader = torch.utils.data.DataLoader(dataset=myDatasetVariableSequenceLengthDataset, batch_size=1, shuffle=False)

losses = []
loss = None
num_epochs = 1
total_steps = len(train_loader)
for epoch in range(num_epochs):
    for i, (features, target) in enumerate(train_loader):

        # convert Double tensor to Float tensor
        features = features.float()

        outputs = model(features)
        
        loss = criterion(outputs, target.float())

        optimizer.zero_grad()
        
        loss.backward()

        optimizer.step()
        if (i+1) % 100 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}' 
                   .format(epoch+1, num_epochs, i+1, total_steps, loss.item()))
    losses.append(loss.item())



torch.Size([749, 3])


RuntimeError: input must have 3 dimensions, got 2

# Multivariate classifier

In [ ]:
# Multivariate time series classification with sktime 


from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

from sktime.classification.compose import ColumnEnsembleClassifier
from sktime.classification.dictionary_based import BOSSEnsemble
from sktime.classification.interval_based import TimeSeriesForestClassifier
from sktime.classification.shapelet_based import MrSEQLClassifier
from sktime.datasets import load_basic_motions
from sktime.transformations.panel.compose import ColumnConcatenator


X, y = load_basic_motions(return_X_y=True)

print("multivariate time series classification with sktime")
print("X shape", X.shape)
print(X.shape)

print("y shape", y.shape)





Univariate classifier